---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "37 13 */4 * *"
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v3.3.0

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: .github/workflows/ci.yml
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Get short commit ref
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
      - name: Build and push ref tag
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: martynas/archlinux:${{ steps.vars.outputs.sha_short }}

      - if: github.ref_name == 'main'
        name: Build and push latest tag
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: martynas/archlinux:latest

      - uses: gautamkrishnar/keepalive-workflow@v1
