---
name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "37 13 */4 * *"
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    name: Validate a Pull Request
    steps:
      - uses: actions/checkout@v1

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v0.0.2
        with:
          file_or_dir: .github/workflows/ci.yml

      - name: build
        uses: docker/build-push-action@v1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: martynas/archlinux
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
